apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ingress.yaml
- app/manifests/deployment.yaml
- app/manifests/service.yaml
- app/manifests/configmap.yaml
- db/deployment.yaml

images:
- name: PING/APP
  newName: somkiat/ping-pong
