apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          # image: PING/APP
          image: somkiat/ping-pong
          env:
            - name: CONNECT_STRING
              valueFrom:
                configMapKeyRef:
                  name: ping-pong-conf
                  key: CONNECT_STRING
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
          imagePullPolicy: Always
